name: Build Common.js

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '24'
        cache: 'npm'
        cache-dependency-path: 'commonjs/package-lock.json'

    - name: Install dependencies
      working-directory: ./commonjs
      run: npm ci

    - name: Build
      working-directory: ./commonjs
      run: npm run build

    - name: Upload build artifact
      uses: actions/upload-artifact@v7
      if: success()
      with:
        name: common-js-build
        path: commonjs/out/Common.min.js
        retention-days: 90
